server:
  port: 8150

  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 192.168.56.101:8080

  redis:
    lettuce:
      pool:
        max-active: 500
        max-wait: 500
        max-idle: 500
        min-idle: 0
    host: 192.168.56.101
    port: 6379

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true


  thymeleaf:
    cache: false

  session:
    store-type: redis

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'



