spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848
    alicloud:
      sms:
        host: https://fesms.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 175622
        appcode: b0563c23aff8428c97a54d4f7f9e28e5


  application:
    name: gulimall-third-party

server:
  port: 30000


minio:
  endpoint: http://192.168.56.101:9010 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
